authors = ["Vladimir Arnautov (mail@pharmcat.net)"]
name = "ClinicalTrialUtilities"
uuid = "535c2557-d7d0-564d-8ff9-4ae146c18cfe"
version = "0.2.2"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
test = ["CSV", "Test", "Plots"]

[compat]
julia = "1.0, 1.1, 1.2, 1.3"
Distributions = "0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22"
StatsBase = "0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32"
DataFrames = "0.19"
QuadGK = "2.0, 2.1"
SpecialFunctions = "0.8, 0.9"
Roots = "0.7, 0.8"
CSV = "0.5"
RecipesBase = "0.7"
